package aplikasi;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import koneksi.koneksi;
import java.io.File;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

public class menuutama extends javax.swing.JFrame {
    koneksi k = new koneksi();
    //Tambahan Waktu
    java.util.Date tglsekarang = new java.util.Date();
    private final SimpleDateFormat smpdtfmt = new SimpleDateFormat("EEEE, dd MMMM yyyy", Locale.getDefault());
    //diatas adalah pengaturan format penulisan, bisa diubah sesuai keinginan.
    private final String tanggal = smpdtfmt.format(tglsekarang);
    /**
     * Creates new form menuutama
     */
    public menuutama() {
        initComponents();
        Locale locale = new Locale ("id","ID");
        Locale.setDefault(locale);
        setLocationRelativeTo(this);
        tgl.setText(tanggal);
        setJam();
    }
    
    public final void setJam(){
    ActionListener taskPerformer = new ActionListener() {

    @Override
    public void actionPerformed(ActionEvent evt)
        {
    String nol_jam = "", nol_menit = "",nol_detik = "";

    java.util.Date dateTime = new java.util.Date();
    int nilai_jam = dateTime.getHours();
    int nilai_menit = dateTime.getMinutes();
    int nilai_detik = dateTime.getSeconds();

    if(nilai_jam <= 9) nol_jam= "0";
    if(nilai_menit <= 9) nol_menit= "0";
    if(nilai_detik <= 9) nol_detik= "0";

    String jam = nol_jam + Integer.toString(nilai_jam);
    String menit = nol_menit + Integer.toString(nilai_menit);
    String detik = nol_detik + Integer.toString(nilai_detik);

    wkt.setText(jam+":"+menit+":"+detik+"");
    }
    };
    new Timer(1000, taskPerformer).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        wkt = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Data_Admin = new javax.swing.JMenuItem();
        Data_Supplier = new javax.swing.JMenuItem();
        Data_Provider = new javax.swing.JMenuItem();
        Proses = new javax.swing.JMenu();
        Pembelian = new javax.swing.JMenuItem();
        Penjualan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        LapKaryawan = new javax.swing.JMenuItem();
        LapDepartemen = new javax.swing.JMenuItem();
        LapStokLimbah = new javax.swing.JMenuItem();
        LapLimbahMasuk = new javax.swing.JMenuItem();
        LapSerahTerima = new javax.swing.JMenuItem();
        Logout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Pelayanan Pembelian Pulsa Dan Paket Data Dherell Cell");
        setBackground(new java.awt.Color(255, 51, 51));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SISTEM PELAYANAN");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo-polos DC.png"))); // NOI18N

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Alamat 1 DC.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PEMBELIAN PULSA DAN PAKET DATA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addComponent(jLabel5))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Jakarta,");

        tgl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tgl.setText("Tanggal");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Waktu : ");

        wkt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        wkt.setText("Waktu");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setText("WIB");

        jMenu1.setText("File");

        jMenuItem1.setText("Tentang Aplikasi");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Input Data Master");

        Data_Admin.setText("Data Admin");
        Data_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Data_AdminActionPerformed(evt);
            }
        });
        jMenu2.add(Data_Admin);

        Data_Supplier.setText("Data Supplier");
        Data_Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Data_SupplierActionPerformed(evt);
            }
        });
        jMenu2.add(Data_Supplier);

        Data_Provider.setText("Data Paket Provider");
        Data_Provider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Data_ProviderActionPerformed(evt);
            }
        });
        jMenu2.add(Data_Provider);

        jMenuBar1.add(jMenu2);

        Proses.setText("Proses");

        Pembelian.setText("Pembelian");
        Pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PembelianActionPerformed(evt);
            }
        });
        Proses.add(Pembelian);

        Penjualan.setText("Penjualan");
        Penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenjualanActionPerformed(evt);
            }
        });
        Proses.add(Penjualan);

        jMenuBar1.add(Proses);

        jMenu3.setText("Laporan");

        LapKaryawan.setText("Data Admin");
        LapKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapKaryawanActionPerformed(evt);
            }
        });
        jMenu3.add(LapKaryawan);

        LapDepartemen.setText("Data Supplier");
        LapDepartemen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapDepartemenActionPerformed(evt);
            }
        });
        jMenu3.add(LapDepartemen);

        LapStokLimbah.setText("Data Stok Paket Provider");
        LapStokLimbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapStokLimbahActionPerformed(evt);
            }
        });
        jMenu3.add(LapStokLimbah);

        LapLimbahMasuk.setText("Data pembelian");
        LapLimbahMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapLimbahMasukActionPerformed(evt);
            }
        });
        jMenu3.add(LapLimbahMasuk);

        LapSerahTerima.setText("Data Penjualan");
        LapSerahTerima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapSerahTerimaActionPerformed(evt);
            }
        });
        jMenu3.add(LapSerahTerima);

        jMenuBar1.add(jMenu3);

        Logout.setText("Keluar");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(Logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(576, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wkt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tgl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(wkt)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
    if (JOptionPane.showConfirmDialog(null, "Yakin Keluar ?", "Form Logout", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        System.exit (0);
    }//GEN-LAST:event_LogoutMouseClicked
    }
    private void PenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenjualanActionPerformed
    new jual().show();
    this.dispose();
    }//GEN-LAST:event_PenjualanActionPerformed

    private void PembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PembelianActionPerformed
        // TODO add your handling code here:
        new beli().show();
        this.dispose();
    }//GEN-LAST:event_PembelianActionPerformed

    private void Data_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Data_AdminActionPerformed
        // TODO add your handling code here:
        new Admin().show();
        this.dispose();
    }//GEN-LAST:event_Data_AdminActionPerformed

    private void Data_ProviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Data_ProviderActionPerformed
        // TODO add your handling code here:
        new Provider().show();
        this.dispose();
    }//GEN-LAST:event_Data_ProviderActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    new Tentang_Aplikasi().show();
    this.dispose();   
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void LapKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapKaryawanActionPerformed
        // TODO add your handling code here:
        try {
            File namafile = new File("src/Laporan/DataAdmin.jasper");
            JasperPrint jp = JasperFillManager.fillReport(namafile.getPath(), null, k.connect());
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_LapKaryawanActionPerformed

    private void LapDepartemenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapDepartemenActionPerformed
        // TODO add your handling code here:
        try {
            File namafile = new File("src/Laporan/DataSupplier.jasper");
            JasperPrint jp = JasperFillManager.fillReport(namafile.getPath(), null, k.connect());
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_LapDepartemenActionPerformed

    private void LapStokLimbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapStokLimbahActionPerformed
        // TODO add your handling code here:
        try {
            File namafile = new File("src/Laporan/DataPaket.jasper");
            JasperPrint jp = JasperFillManager.fillReport(namafile.getPath(), null, k.connect());
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_LapStokLimbahActionPerformed

    private void LapLimbahMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapLimbahMasukActionPerformed
        // TODO add your handling code here:
        try {
            File namafile = new File("src/Laporan/DataPembelian.jasper");
            JasperPrint jp = JasperFillManager.fillReport(namafile.getPath(), null, k.connect());
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_LapLimbahMasukActionPerformed

    private void LapSerahTerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapSerahTerimaActionPerformed
        // TODO add your handling code here:
        try {
            File namafile = new File("src/Laporan/DataPenjualan.jasper");
            JasperPrint jp = JasperFillManager.fillReport(namafile.getPath(), null, k.connect());
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_LapSerahTerimaActionPerformed

    private void Data_SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Data_SupplierActionPerformed
        new Supplier().show();
        this.dispose();
    }//GEN-LAST:event_Data_SupplierActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuutama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Data_Admin;
    private javax.swing.JMenuItem Data_Provider;
    private javax.swing.JMenuItem Data_Supplier;
    private javax.swing.JMenuItem LapDepartemen;
    private javax.swing.JMenuItem LapKaryawan;
    private javax.swing.JMenuItem LapLimbahMasuk;
    private javax.swing.JMenuItem LapSerahTerima;
    private javax.swing.JMenuItem LapStokLimbah;
    private javax.swing.JMenu Logout;
    private javax.swing.JMenuItem Pembelian;
    private javax.swing.JMenuItem Penjualan;
    private javax.swing.JMenu Proses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel tgl;
    private javax.swing.JLabel wkt;
    // End of variables declaration//GEN-END:variables
}
